# Ejercicios Numpy II

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np
my_array = np.arange(10)
print(my_array[-1::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [[8 7]] del array `my_array`

In [3]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [[2 1 0]] de `my_array`

In [4]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
matrix_4 = np.arange(1,21)
matrix_4= matrix_4.reshape((4,5))
print(matrix_4)
matrix_5 = np.flip(matrix_4)
matrix_5

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [6]:
matrix_4[0:2,0:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [74]:
matrix_4[0::2,0::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [82]:
matrix_4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [88]:
matrix_4[:3:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [70]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
lista= []
for i in x:
    if i == "Loro":
        lista.append(i)
array_x = np.array(lista)
array_x

array(['Loro', 'Loro'], dtype='<U4')

In [71]:
sin_loro = x[x == "Loro"]
sin_loro

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [38]:
array_6 = np.arange(20)
array_6 = np.reshape(array_6,(2,5,2))
array_6

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del **ejercicio 4**
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [40]:
array_7 = np.flip(matrix_4)
array_7

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [51]:
import sys
array_zero = np.zeros(10)
print(sys.getsizeof(array_zero))
array_zero[3] = 1
array_zero

184


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [49]:
vector_1c = np.arange(10,50)
print(vector_1c)
vector_2c = np.flip(vector_1c)
print(vector_2c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [[1,2,0,0,4,0]]. El output sería [[0, 1, 4]]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [84]:
ve = [1,2,0,0,4,0]
ve_1 = np.nonzero(ve)
print(ve_1)


(array([0, 1, 4], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [56]:
array_8 = np.random.randint(1000,size=(10,10))
array_8

array([[792, 729, 663, 290, 267, 727, 722,  81,  37, 835],
       [781, 618, 545, 678, 852, 585, 160, 345, 834, 334],
       [682, 409, 523, 638, 754, 898, 178, 740, 409, 555],
       [171, 838, 837,  63, 624, 443, 492, 670, 880, 710],
       [796, 595, 716, 908, 959, 258, 253, 413,  51, 849],
       [685, 785, 102, 779, 203, 167, 371, 430, 579, 659],
       [119, 298, 363, 254, 296, 483,   4, 826,  99, 256],
       [722,  46, 996, 403, 279, 831, 184, 656, 129, 944],
       [896, 373, 873,  72, 846,   5, 706, 835, 437,   2],
       [768, 631, 642, 791, 580, 582, 419, 529, 686, 360]])

In [57]:
np.amax(array_8)

996

In [58]:
np.amin(array_8)

2

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [67]:
vector_3 = np.random.randint(30,size=30)
print(vector_3)
np.mean(vector_3)

[11 18 12 21 19 24 15  4 21 12 20  3 11  9  5 28 26 21 25 11 14 16 19 12
 10  0 18 26 25 29]


16.166666666666668

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [91]:
ones_matrix = np.ones((3,3),dtype=int)
print(ones_matrix)
ones_matrix[1][1] = 0
ones_matrix


[[1 1 1]
 [1 1 1]
 [1 1 1]]


array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [58]:
matrix_CE = np.zeros((8,8),dtype=int)
print(matrix_CE)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [61]:
matrix_CE[::2,1::2]=1
matrix_CE[1::2,::2]=1
print(matrix_CE)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [68]:
a = np.array([[0,1],[1,0]])
print(np.tile(a,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [28]:
matrix_19 = np.random.randint(50,size=(5,5))
media =np.mean(matrix_19)
d_tip =np.std(matrix_19)

print(matrix_19)
print(media)
print(d_tip)
matrix_20 = matrix_19-media
normalizada = matrix_20/d_tip
normalizada

[[30 10 21 47 37]
 [12 45 48 47 20]
 [28 31 40  3 14]
 [34 21  1  0 14]
 [42  5 35  1 25]]
24.44
15.687141230957284


array([[ 0.35443042, -0.92049914, -0.21928788,  1.43812054,  0.80065576],
       [-0.79300618,  1.31062758,  1.50186702,  1.43812054, -0.28303436],
       [ 0.22693746,  0.41817689,  0.99189519, -1.36672448, -0.66551323],
       [ 0.60941633, -0.21928788, -1.49421744, -1.55796392, -0.66551323],
       [ 1.11938815, -1.23923153,  0.67316281, -1.49421744,  0.03569803]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya todos los elementos entre el 3 y el 8, por el valor -1
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [43]:
secuencia = np.arange(11)


In [47]:
secuencia1 = np.arange(11)
secuencia1[3:9]= -1
secuencia1

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

In [49]:
secuencia2 = np.arange(11)
secuencia2[3:9]= -secuencia2[3:9]
secuencia2


array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

## Ejercicio 21 
#### Bonus track. Mini hundir la flota para ir practicando.
##### Te ayudará a entender la lógica de la tarea Hundir la Flota.
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.